name = "xaostech-portfolio"
compatibility_date = "2025-12-31"
main = "src/worker.ts"
send_metrics = false

routes = [
  { pattern = "portfolio.xaostech.io/*", zone_name = "xaostech.io" },
  { pattern = "xaostech.io/portfolio/*", zone_name = "xaostech.io" }
]

[[env.production.r2_buckets]]
binding = "IMG"
bucket_name = "img"

[env.production]

[env.testing]
routes = [
  { pattern = "portfolio.testing.local/*", zone_name = "localhost" },
  { pattern = "testing.local/portfolio/*", zone_name = "localhost" }
]
